Add API
JulianFrattini/cira pull request #22
Opened 2022-11-01 16:44 UTC by JulianFrattini

This PR adds an API that exposes the CiRA functionality in a RESTful service via [FastAPI](https://fastapi.tiangolo.com/) and therefore closes #16. The feature branch includes unit-, integration-, and system-level tests for the API functionality.

2022-11-05 11:00 UTC, andreas-bauer requested changes
Overall a solid implementation of a web API.

In my humble opinion, comments within a function, like "serialize labels",  should only be used when other measurements are not suitable. Often renaming the var or rextracting the functionality into a own function with a good name resolves the need for a comment.

2022-11-07 13:34 UTC, JulianFrattini commented on src/api/service.py
> +        # serialize all labels and return them
Interesting proposal. I will adjust the new code with respect to this idea but adjusting the existing code base will take additional effort. I will consider it for a rainy day.

2022-11-07 13:38 UTC, JulianFrattini commented on src/api/service.py
> +    def recover_labels(self, sentence: str, labels: list) -> list[Label]:
The purpose of the method is to get the deserialized labels. Rather than reassigning the paths, I changed the method name to reflect this purpose.

2022-11-07 13:39 UTC, JulianFrattini commented on src/api/service.py
> +        serialized = graph.to_dict()
I made the variables more explicit with meaningful names and type hints.

2022-11-07 13:47 UTC, JulianFrattini commented on src/data/graph.py
> +    nodes: list[Node] = []
The functionality has now been extracted to class methods of nodes and edges, which should make this method much more readable.

2022-11-07 16:58 UTC, andreas-bauer requested changes
`test/app/test_app_isolated.py`: Could you change the status code assertions to use const values like in the other test files.

2022-11-07 16:58 UTC, andreas-bauer commented on test/app/test_app_isolated.py
> +    assert response.status_code == 200
This test file should also use HTTP status consts instead of direct values

2022-11-07 18:32 UTC, merged